### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/cliente/1 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{
    "nome" : "Luís Eduardo Bernardino Luz",
    "cpf" : "00000000000",
    "telefone" : "12345678901",
    "marca_fiado" : true,
    "dia_fiado" : 5,
    "senha" : "senhaclienteteste"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/3 HTTP/1.1
content-type: application/json

{
    "nome" : "Luís Eduardo Bernardino Luz EDITADO",
    "cpf" : "00987654321",
    "telefone" : "10987654321",
    "marca_fiado" : true,
    "dia_fiado" : 5,
    "senha" : "senhaclientetestefiado"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/3 HTTP/1.1

